### ISSUE TITLE
can't figure out how to accelerate

### ISSUE THREAD

**Issue by ii3urNz** [JR1811/Boatism#7]
hi,
i've got the motor on my boat filled with gas and it's starting but when driving the boat charakter is rowing at normal speed.

**Comment by JR1811** [comment]
Hello,

Currently, you can change the power level, if the engine is turned on, by scrolling with the mouse wheel. Rowing is not needed to drive with the engine, but it will give a good speed increase on top of the standard engine output. I have planned to implement an additional screen, some more UI elements and custom key binds to improve the user experience in the future.

I hope this fixed the issue.

**Comment by JR1811** [comment]
Just to let you know. Boatism has now also key binds which you can set up in your settings (by default unbound).

It is available in the newest version 0.1.1 on [GitHub](https://github.com/JR1811/Boatism/releases/tag/0.1.1) or [Modrinth](https://modrinth.com/mod/boatism/version/0.1.1)
